### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by NixFey** [ispoljari/react-weather-app#1]
Hey! Looks like you included some API keys in your commits. You might want to consider changing the keys and moving them into a file that isn't tracked by Git

**Comment by ispoljari** [comment]
Hey Evan,
thanks for pointing this out to me. 

However this was just a tutorial project for me in which I wanted to implement some API calls using React. So i created this semi-serious weather app which uses a key which I had no intention in protecting.
Normally i use environment variables to protect my keys, and the keys from local environment aren't tracked by git.

But thank you for checking out my projects in such detail. I really appreciate it.

All the best,
Ivan
